### ISSUE TITLE
Ability to add headers to the token requests

### ISSUE THREAD

**Issue by koenr-bc** [badgateway/oauth2-client#100]
I would like the ability to add custom headers to requests made by OAuth2Client.OAuth2Client

Example usage would be something like;

```
const client = new Client({
  server: 'https://auth-server.example/',

  clientId: '...',

  clientSecret: '...',

  additionalHeaders: '...',

});
```

Which I guess should be used in the client.ts's async request method

**Comment by evert** [comment]
Hi @koenr-bc ,

I just published a new release that includes #86 . That change lets you add a custom implementation of fetch, and one way you could use this is by adding your own headers.

With Javascript, you could do this (roughly) this way:

```
const client = new Client({
  server: 'https://auth-server.example/',

  clientId: '...',
  clientSecret: '...',

  fetch: (...args) => {
     const request = new Request(...args);
     request.headers.append('X-Header', 'X-Value');
     return fetch(request);
  }

});
```

I didn't test this.

Also I'm curious *why* you need this. Is this a public API that requires something unique?

**Comment by bradjones1** [comment]
FWIW I include information like the app version in headers (user-agents like Chrome have poor support for customizing the user-agent header itself) for telemetry, could be a similar use case.

**Comment by koenr-bc** [comment]
Thanks this worked! was needed to add debugging information
