### ISSUE TITLE
Automatic refresh with PKCE and `FetchWrapper` (codeverifer not included)

### ISSUE THREAD

**Issue by debater-coder** [badgateway/oauth2-client#102]
Hello,

I'm using this library with PKCE and `FetchWrapper` and I am having trouble with the refresh tokens. I instantiate `FetchWrapper` like so:

```ts
const fetchWrapper = new OAuth2Fetch({
  client,

  getNewToken: () => {
    // Set the status to expired
    useAuthStore.setState({ status: AuthStatus.EXPIRED });

    return null; // Fail this step, we don't want to log out until the user does so explicitly
  },

  storeToken: (token) => {
    useAuthStore.setState({
      token,
    });
  },

  getStoredToken: () => useAuthStore.getState().token,
});
```

From my understanding, this fetchWrapper should automatically refresh the tokens when they expire and it tries to send a request. 
![image](https://github.com/badgateway/oauth2-client/assets/52619668/5b329258-5b85-45c6-80eb-94bced3453cd)
Indeed, it does appear that it is sending a refresh request to the token endpoint. However, the server rejects it, because it does not include the `code_verifier`. Before using this library, I built a custom solution which does send the code_verifier in the refresh requests, and I can verify that if it sends that then it does work.

I believe the solution is to make some API change that allows the `FetchWrapper` to access the `code_verifier` (potentially by storing the `code_verifier` in the `OAuth2Token`).

Thank you.

**Comment by debater-coder** [comment]
I made some changes to support this in #104.

**Comment by evert** [comment]
Hi @debater-coder , I was indeed a bit surprised to read about this. The PKCE stuff, as I understood it only exists to mitigate security issues with the initial redirects/handshakes but once you have an access (and refresh token) these concerns don't exist.

So requiring the argument during the refresh, and thus also requiring clients to hold onto their initial code_verifier for the entire duration of the session + every refresh is really surprising to me.

Happy to discuss this further though. Is this a public API?

**Comment by debater-coder** [comment]
No, it's not a public API. I should be able to get a chance to talk to the maintainer of the API today and see if I can get this changed. The PKCE implementation for this provider is kind of shoehorned in so it's likely custom and other providers wouldn't have this 'bug'.

**Comment by debater-coder** [comment]
Sorry for not getting back sooner, the issue has been fixed on the provider's side.

**Comment by evert** [comment]
Thanks for following up, nice to know I didn't misinterpret the spec =)
