### ISSUE TITLE
Add an optional scope parameter to the client.refreshToken method

### ISSUE THREAD

**Issue by superosku** [badgateway/oauth2-client#127]
Refresh token grant takes an optional parameter `scope` according to the [oauth2 spec](https://datatracker.ietf.org/doc/html/rfc6749#section-6)

The client just takes the (refresh) token as a parameter [link](https://github.com/badgateway/oauth2-client/blob/main/src/client.ts#L113):

```
  async refreshToken(token: OAuth2Token): Promise<OAuth2Token> {
```

How about adding an optional scope to the client.refreshToken method.

Can be bypassed for now by using the `request('tokenEndpoint', body)` method directly.

Also:
README.md seems to have the method name incorrectly as refresh instead of refreshToken.

Thanks!

**Comment by evert** [comment]
Not against adding this, but I am curious about the use-case. Given that omitting the scope is equal to keeping the original scope, the only real reason I see to specify this is to reduce the scope. Is this what you're using it for, or are you talking to a server that requires it no matter what?
