### ISSUE TITLE
/token: don't send client_id in body

### ISSUE THREAD

**Issue by bbigras** [badgateway/oauth2-client#71]
see:
https://github.com/HeroicKatora/oxide-auth/issues/145

basically it seems that you should only use `authorization: Basic`

**Comment by evert** [comment]
Hi @bbigras , I think #72 fixes this and also your other issue (#70).

If a `clientSecret` is passed in the constructor, we will no longer add `clientId` and `clientSecret` to the body, they are both now set in the `Authorization: Basic` header.

If that works for you, I will close this ticket and release a new version of this package.

**Comment by bbigras** [comment]
Is there an easy way for me to use your github repo in package.json?

I tried this:
```json
  "dependencies": {
    "@badgateway/oauth2-client": "badgateway/oauth2-client",
```

but I got:
```
Failed to resolve entry for package "@badgateway/oauth2-client". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@badgateway/oauth2-client". The package may have incorrect main/module/exports specified in its package.json.
```

**Comment by bbigras** [comment]
> If that works for you, I will close this ticket and release a new version of this package.

It seems to work. Thanks!
