### ISSUE TITLE
endpoint domain addresses could differ.

### ISSUE THREAD

**Issue by cgencer** [badgateway/oauth2-client#77]
new endpoint as follows
"accounts.google.com/o/oauth2/v2/auth"
"www.googleapis.com/oauth2/v4/token"

as per google, 
<img width="635" alt="Screen Shot 2022-09-11 at 13 42 50" src="https://user-images.githubusercontent.com/3399683/189523248-cbb3579f-298d-4926-9ac7-c04d3b04470e.png">
endpoints could differ, so it could be easier to have full url's on the configuration.
and a few real-world examples with public api's could be nice...

**Comment by evert** [comment]
The configuration resolves relative urls based on the `server` the same way a browser would. This means that if you specified an absolute url, those urls would be used as-is. And given that they support the discovery document, in theory you only have to specify `discoveryEndpoint`, which appears to be `https://accounts.google.com/.well-known/openid-configuration`

Definitely open to having examples in the readme! Once you got it working, lmk what configuration you used and ill edit it in (or send a PR!)
