### ISSUE TITLE
Abort and retry any other in-flight requests at time of refresh

### ISSUE THREAD

**Issue by bradjones1** [badgateway/oauth2-client#80]
I'm trying to figure out how to handle the situation where any number of requests may be in-flight at a moment when token refresh occurs as the result of a `401`.

In particular I'm debugging a situation in which I have, say, 8 parallel requests and only one is refreshing, and strangely (not sure if it's a result of the middleware or something else) the others continue without use of the middleware altogether.

I _think_ the answer would be some sort of global state/singleton which coordinates an AbortController and signals all in-flight requests, and then retries them after the refresh?

**Comment by evert** [comment]
Closing due to no feedback
